---
services:
  music-explorer:
    image: ghcr.io/mark-me/music_explorer:v0.0.1
    container_name: music-explorer
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /data/music-explorer:/data
    ports:
      - 5000:5000
  redis:
    image: redis:8.0-M03-alpine3.21
    container_name: redis
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 6379:6379
    volumes:
      - /data/music-explorer/redis:/data

