site_name: Music Explorer Docs
site_url: https://mark-me.github.io/music-explorer/

theme:
  name: "material"
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    scheme: slate
    primary: blue grey
  features:
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress

plugins:
  - mkdocstrings
  - search

nav:
  - Music Explorer Docs: index.md
  - Deployment: Deployment.md
  - Web app UI: UI.md
  - Analytics: Analytics.md
  - Discogs ETL: DiscogsETL.md
  - API reference: ApiReference.md

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format