site_name: Music Explorer Docs
site_url: https://mark-me.github.io/music-explorer/

theme:
  name: "material"
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    scheme: slate
    primary: blue grey
  features:
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress

plugins:
  - mkdocstrings
  - search

nav:
  - Music Explorer Docs: index.md
  - Discogs ETL: DiscogsETL.md
  - API reference: reference.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format