site_name: Music Explorer Docs
site_url: https://mark-me.github.io/music-explorer/

theme:
  name: "material"

plugins:
  - mkdocstrings
  - search
  - mermaid2
  - panzoom:
      # images: true
      # mermaid: true # old config
      full_screen: true
      always_show_hint: true
      key: "alt"
      include_selectors:
        - img

nav:
  - Music Explorer Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom